### ISSUE TITLE
Future plans

### ISSUE THREAD

**Issue by jordanrule** [praeducer/conversational-agent#1]
Can you detail more about using Neona to help students find jobs in AI?  I may be able to explore some of the ideas for PR.

**Comment by praeducer** [comment]
Super cool! At the time I was thinking of helping students understand the possible career paths in AI, have them choose one, and then present learning content related to those career paths. Similar to the "Learn by Roles" experience here: https://aws.amazon.com/training/learn-about/

btw if you want to join my freelancer/entrepreneur community, https://www.hyperbloom.ai/, and work with a team on this, shoot me an email at paul@hyperbloom.ai!

**Comment by jordanrule** [comment]
Interesting!  Closing this since we synced over email.
